version: 2
jobs:
  build:
    docker:
    - image: maven:3.5.0-jdk-8
    working_directory: ~/app
    steps:
    - checkout

    - restore_cache:
        keys:
        - gplay-{{ .Environment.cache_version }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

    - run:
        name: Create test properties file
        command: |
          mkdir -p target/test-classes
          cd target/test-classes
          if [ ! -f gplaymusic.properties ]; then
              printf "auth.username=${auth_username}\n" >> gplaymusic.properties
              printf "auth.password=${auth_password}\n" >> gplaymusic.properties
              printf "auth.android_id=${auth_android_id}\n" >> gplaymusic.properties
              printf "auth.free.username=${auth_free_username}\n" >> gplaymusic.properties
              printf "auth.free.password=${auth_free_password}\n" >> gplaymusic.properties
              printf "auth.free.android_id=${auth_free_android_id}\n" >> gplaymusic.properties
              printf "auth.free.token=${auth_free_token}\n" >> gplaymusic.properties
              printf "auth.token=${auth_token}\n" >> gplaymusic.properties
              printf "test.track.playlist=${test_track_playlist}\n" >> gplaymusic.properties
          fi

    - run:
        command: mvn test
        name: Running unit tests
        when: always

    - run:
        command: mvn javadoc:javadoc
        name: Creating Javadoc

    - run:
        name: Copy test reports
        when: always
        command: |
          mkdir -p target/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} target/junit/ \;

    - store_test_results:
        path: target/junit/
    - store_artifacts:
        path: target/junit/

    - deploy:
        command: mvn site -P report
        name: Building reports
    - store_artifacts:
        path: target/site/

    - save_cache:
        key: gplay-{{ .Environment.cache_version }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
